# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.orders_ids_ap import OrdersIdsAP  # noqa: F401,E501
from swagger_server import util


class InlineResponse4001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, validation_error: OrdersIdsAP=None):  # noqa: E501
        """InlineResponse4001 - a model defined in Swagger

        :param validation_error: The validation_error of this InlineResponse4001.  # noqa: E501
        :type validation_error: OrdersIdsAP
        """
        self.swagger_types = {
            'validation_error': OrdersIdsAP
        }

        self.attribute_map = {
            'validation_error': 'validation_error'
        }
        self._validation_error = validation_error

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse4001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400_1 of this InlineResponse4001.  # noqa: E501
        :rtype: InlineResponse4001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def validation_error(self) -> OrdersIdsAP:
        """Gets the validation_error of this InlineResponse4001.


        :return: The validation_error of this InlineResponse4001.
        :rtype: OrdersIdsAP
        """
        return self._validation_error

    @validation_error.setter
    def validation_error(self, validation_error: OrdersIdsAP):
        """Sets the validation_error of this InlineResponse4001.


        :param validation_error: The validation_error of this InlineResponse4001.
        :type validation_error: OrdersIdsAP
        """
        if validation_error is None:
            raise ValueError("Invalid value for `validation_error`, must not be `None`")  # noqa: E501

        self._validation_error = validation_error
