# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.couriers_ids_ap import CouriersIdsAP  # noqa: F401,E501
from swagger_server import util


class InlineResponse400(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, validation_error: CouriersIdsAP=None):  # noqa: E501
        """InlineResponse400 - a model defined in Swagger

        :param validation_error: The validation_error of this InlineResponse400.  # noqa: E501
        :type validation_error: CouriersIdsAP
        """
        self.swagger_types = {
            'validation_error': CouriersIdsAP
        }

        self.attribute_map = {
            'validation_error': 'validation_error'
        }
        self._validation_error = validation_error

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse400':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400 of this InlineResponse400.  # noqa: E501
        :rtype: InlineResponse400
        """
        return util.deserialize_model(dikt, cls)

    @property
    def validation_error(self) -> CouriersIdsAP:
        """Gets the validation_error of this InlineResponse400.


        :return: The validation_error of this InlineResponse400.
        :rtype: CouriersIdsAP
        """
        return self._validation_error

    @validation_error.setter
    def validation_error(self, validation_error: CouriersIdsAP):
        """Sets the validation_error of this InlineResponse400.


        :param validation_error: The validation_error of this InlineResponse400.
        :type validation_error: CouriersIdsAP
        """
        if validation_error is None:
            raise ValueError("Invalid value for `validation_error`, must not be `None`")  # noqa: E501

        self._validation_error = validation_error
