# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrdersCompletePostRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, courier_id: int=None, order_id: int=None, complete_time: str=None):  # noqa: E501
        """OrdersCompletePostRequest - a model defined in Swagger

        :param courier_id: The courier_id of this OrdersCompletePostRequest.  # noqa: E501
        :type courier_id: int
        :param order_id: The order_id of this OrdersCompletePostRequest.  # noqa: E501
        :type order_id: int
        :param complete_time: The complete_time of this OrdersCompletePostRequest.  # noqa: E501
        :type complete_time: str
        """
        self.swagger_types = {
            'courier_id': int,
            'order_id': int,
            'complete_time': str
        }

        self.attribute_map = {
            'courier_id': 'courier_id',
            'order_id': 'order_id',
            'complete_time': 'complete_time'
        }
        self._courier_id = courier_id
        self._order_id = order_id
        self._complete_time = complete_time

    @classmethod
    def from_dict(cls, dikt) -> 'OrdersCompletePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrdersCompletePostRequest of this OrdersCompletePostRequest.  # noqa: E501
        :rtype: OrdersCompletePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def courier_id(self) -> int:
        """Gets the courier_id of this OrdersCompletePostRequest.


        :return: The courier_id of this OrdersCompletePostRequest.
        :rtype: int
        """
        return self._courier_id

    @courier_id.setter
    def courier_id(self, courier_id: int):
        """Sets the courier_id of this OrdersCompletePostRequest.


        :param courier_id: The courier_id of this OrdersCompletePostRequest.
        :type courier_id: int
        """
        if courier_id is None:
            raise ValueError("Invalid value for `courier_id`, must not be `None`")  # noqa: E501

        self._courier_id = courier_id

    @property
    def order_id(self) -> int:
        """Gets the order_id of this OrdersCompletePostRequest.


        :return: The order_id of this OrdersCompletePostRequest.
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: int):
        """Sets the order_id of this OrdersCompletePostRequest.


        :param order_id: The order_id of this OrdersCompletePostRequest.
        :type order_id: int
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id

    @property
    def complete_time(self) -> str:
        """Gets the complete_time of this OrdersCompletePostRequest.


        :return: The complete_time of this OrdersCompletePostRequest.
        :rtype: str
        """
        return self._complete_time

    @complete_time.setter
    def complete_time(self, complete_time: str):
        """Sets the complete_time of this OrdersCompletePostRequest.


        :param complete_time: The complete_time of this OrdersCompletePostRequest.
        :type complete_time: str
        """
        if complete_time is None:
            raise ValueError("Invalid value for `complete_time`, must not be `None`")  # noqa: E501

        self._complete_time = complete_time
