# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OrdersCompletePostResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: int=None):  # noqa: E501
        """OrdersCompletePostResponse - a model defined in Swagger

        :param order_id: The order_id of this OrdersCompletePostResponse.  # noqa: E501
        :type order_id: int
        """
        self.swagger_types = {
            'order_id': int
        }

        self.attribute_map = {
            'order_id': 'order_id'
        }
        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'OrdersCompletePostResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OrdersCompletePostResponse of this OrdersCompletePostResponse.  # noqa: E501
        :rtype: OrdersCompletePostResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> int:
        """Gets the order_id of this OrdersCompletePostResponse.


        :return: The order_id of this OrdersCompletePostResponse.
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: int):
        """Sets the order_id of this OrdersCompletePostResponse.


        :param order_id: The order_id of this OrdersCompletePostResponse.
        :type order_id: int
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")  # noqa: E501

        self._order_id = order_id
